### ISSUE TITLE
OpenShift routes for KServe InferenceServices

### ISSUE THREAD

**Issue by israel-hdez** [opendatahub-io/odh-model-controller#59]
In KServe, the URL where an InferenceService can be reached is reported in the same InferenceService. For example, this is a sample output when querying InferenceServices:

```
$ oc get isvc -A
NAMESPACE            NAME                      URL                                                                            READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                       AGE
kserve-ci-e2e-test   isvc-sklearn-v2-mixed     http://isvc-sklearn-v2-mixed-kserve-ci-e2e-test.apps.openshift-cluster.com     True           100                              isvc-sklearn-v2-mixed-predictor-00001     6d6h
kserve-ci-e2e-test   isvc-tensorflow-runtime   http://isvc-tensorflow-runtime-kserve-ci-e2e-test.apps.openshift-cluster.com   True           100                              isvc-tensorflow-runtime-predictor-00001   6d6h
```

The issue is that the specified URL is not reachable in OpenShift.

**Describe the solution you'd like**

KServe assumes a wildcard DNS configuration, as mentioned here: 
* https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#configure-dns (See _Real DNS_ tab)

Typically, in OpenShift, a similar DNS configuration is already set. However, while KServe assumes that the DNS configuration points to Istio Ingress Gateway, in OpenShift the DNS configuration points to OpenShift's Ingress.  This is the reason of seeing the generic "Application is not available" page when trying to access the URLs specified on the InferenceServices.

Since the URLs are hitting OpenShift's Ingress, it turns out that it is a matter of creating the right OpenShift Route, in order to properly enable the InferenceService endpoints. So, **the goal in this ticket is to create these missing Route resources**.

For example, the following route will make reachable the InferenceService `isvc-sklearn-v2-mixed` that is present in the example above:

```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: isvc-sklearn-v2-mixed-kserve-ci-e2e-test
  namespace: istio-system
spec:
  host: isvc-sklearn-v2-mixed-kserve-ci-e2e-test.apps.openshift-cluster.com
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
```

NOTE that:
* The target service is the Istio ingress gateway. This is fixed.
* The Routes should always be created in the Service Mesh control plane namespace, because that's the namespace where the Istio Ingress Gateway lives.
* In the provided examples, the Route is an HTTPS route, but the InferenceService displays a plain HTTP URL. The protocol at the InferenceService should be honored when creating the Route.
* The Route should NOT be created if the URL of the InfrenceService is an "in-cluster URL".
* The Route should be created only for KServe InferenceServices - not ModelMesh, where there is already a different logic.
